### ISSUE TITLE
.NET SDK download issues 

### ISSUE THREAD

**Issue by javeriaanwer** [wiris/moodle-tinymce_tiny_mce_wiris#17]
We are using Wiris demo version connecting our application to your server at  www.wiris.net/demo/. Until now we can get formula in mathML format but we want to convert it as image, we want to use solution mentioned over http://www.wiris.com/editor/docs/servicesapis#render. As we tried to download .Net SDK we get Access denied error, from where can we try above solution or any link that can provide “com.wiris.editor.services” dll.

**Comment by wirismath** [comment]
You can download .NET SDK if you purchase a license. For the details on the server components license you should contact sales@wiris.com.
