### ISSUE TITLE
chemistry and math buttons cause editor confusion

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-tinymce_tiny_mce_wiris#2]
We have both the Chemistry button set and the Math button set available in our editors.  In both tinymce and atto, if one of the editors is brought up, then closed, and the other button is pressed it will only change the title for the editor and not the button configurations.  (for us chemistry set seems to take over)

To test:
open an editor and have the chemistry AND math set available
Click the chemistry set.
Verify the title and the button set are correct for the wiris editor.
Close the wiris popup.
Open the math set.
Verify the title is correct but the button set is still chemistry.

**Comment by manuelwiris** [comment]
@Syxton 

This issue is fixed in our last release 4.1.1.1361
