### ISSUE TITLE
mathtype and chemtype icon paths are incorrect

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-tinymce_tiny_mce_wiris#49]
Using the latest release of filter and tinymce and atto.
Atto works as expected.  The tinymce editor doesn't have  a correct path to the icons.

![image](https://user-images.githubusercontent.com/989354/90171122-0698b180-dd6f-11ea-8d87-79f6adb4aff3.png)
![image](https://user-images.githubusercontent.com/989354/90171223-292aca80-dd6f-11ea-99fb-640e9f845468.png)

**Comment by dcanetma** [comment]
Hi, @Syxton 

We'll fix this issue on our next release.

Thanks for your feedback.

**Comment by dcanet-at-wiris** [comment]
Last release should fix this issue.
